### ISSUE TITLE
test.html doesn't work anymore

### ISSUE THREAD

**Issue by musicin3d** [chrismbryant/amazon-confidence-interval#18]
I've attempted to fix this. I added `type="module"` to the script tag for `calculations.js`, but then it failed to find the stdlib file. I tried the full path to the file, but then Chrome complained that the file didn't provide a default export. I'm pretty sure Webpack does some extra work to make it easier on us. I thought about skipping the import altogether, but conditional imports are highly experimental and seemingly unsupported in Chrome. We may just need to delete `test.html` and find another way to experiment.

**Comment by aeciorc** [comment]
I'm not sure how you guys wanted to use test.html, but you could point to the bundled files directly, e.g: https://github.com/chrismbryant/amazon-confidence-interval/blob/test-html/src/shared/test.html

--Update--
I think the reason it doesn't work is because stdlib uses CommonJS modules, not es6 modules. I 
 think you are right that webpack does some magic to let us uses "import" with cjs

**Comment by aeciorc** [comment]
(didn't meant to close the issue)

**Comment by musicin3d** [comment]
Personally, I just write what I need into the bundle and reload the page.
But I would understand if someone else wanted to use Chrome's console to
hack around. If Chris originally added the file, then I'd say it comes down
to whatever is easy for him to work with. I want to respect that non-web
developers might have a different workflow.

**Comment by chrismbryant** [comment]
Thanks for the consideration, @musicin3d ! Working on adding some visualizations today, I've adjusted my workflow to what you said (bundling and reloading), and that totally works fine for me. So I'll delete the `test.html` file in my next pull request
